name: Markdown Link Check

on:
  pull_request:
    branches:
      - main
  push:

jobs:
  markdown-link-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: gaurav-nelson/github-action-markdown-link-check@1.0.13
        with:
          use-quiet-mode: 'yes'
          use-verbose-mode: 'no'
